spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot?serverTimezone=Asia/Seoul
    username: java
    password: java

mybatis:
  type-aliases-package: com.itwillbs.trip.domain
  mapper-locations:
    - classpath:mapper/**/*.xml